---
title: "nhsrtt: a package for seeing how changes in future treatment capacity affect the waiting list size and performance"
categories:
  - # Enter categories here, with each category on its own line with a - preceding it. Please also include the language as a category to aid with filtering.
title-block-banner: ../../banner.png
status: '<span style="color: #888888FF>Silver</span>' # Delete as appropriate
image: # provide a relative filepath to an image that will appear in the listing page. If you don't have one, delete this line entirely and a placeholder image will be used.
author:
  - name: # Please include your name (so we can appropriately credit you for authoring this page)
    affiliation: # Optionally (but preferred), please include your organisation
    linkedin: # If you're happy to share your linkedin, please do
    website: # If you have a personal website you'd like to share, please do
    orcid: # If you have an ORCID (a unique researcher identifier) you'd like to share, please do
    github: # If you have a github you'd be happy to share, please do
pub-info:
  language: '<i class="fa-brands fa-r-project"></i>' # Delete as appropriate
  abstract: |
    Write a short descrption that would appear on the listing page to help people decide whther they want more information.
  links:
  - name: Code - Model
    url: https://github.com/nhs-bnssg-analytics/NHSRtt
    icon: fa-brands fa-github
  - name: Code - Shiny App
    url: https://github.com/nhs-bnssg-analytics/RTT_compartmental_modelling
    icon: fa-brands fa-github
  - name: Documentation - Model
    url: https://nhs-bnssg-analytics.github.io/NHSRtt/
    icon: fa-solid fa-book
  - name: Documentation - Shiny App
    url: https://nhs-bnssg-analytics.github.io/RTT_compartmental_modelling/
    icon: fa-solid fa-book
  - name: Paper
    url: # Enter a URL here if relvant
    icon: fa-solid fa-file-contract
  - name: PyPi
    url: # Enter a URL here if relvant
    icon: fa-solid fa-brands fa-python
  - name: CRAN
    url: # Enter a URL here if relvant
    icon: fa-solid fa-brands fa-r-project
  - name: Website
    url: # Enter a URL here if relvant
    icon: fa-solid fa-globe
---

The tool supports scenario testing and planning for elective care pathways by translating patient flow data into projections of waiting list size and treatment demand.

The tool uses entirely publically available data, and is currently updated with new data once a month.

The core idea is to implement a stock-and-flow model of activity: patients flow into the waiting-list (‘stock’), are treated or removed (‘outflow’), and the model tracks how these stocks evolve under different demand and capacity conditions.

The second repository contains a packaged shiny app that calls on the main model, allowing users to experiment with different scenarios without having to change parameters in code.

:::{.callout-info}
### Rationale for Rating
13/11/2025 SR: This work has been undertaken by an experienced team of modellers. There is excellent documentation and good automated test coverage.
However, it is not yet available on CRAN, requiring the code to be installed from GitHub, so it has not undertaken the review process that packages on CRAN go through.
:::
