name: "New Package, Project or Tool Submission"
description: "Submit a new package, project or tool to the atlas"
title: "Add new package, project or tool: [NAME]"
labels: ["submission"]

body:
  - type: input
    id: model_name
    attributes:
      label: Package, project or tool name
      placeholder: e.g. vidigi, bupaR, SimPy  
      description: Replace this with the name that should appear when visitors are scrolling through the packages, projects and tools page.
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Short summary
      description: A short summary of what this package, project or tool does. This should be between 50 and 200 words. It will be displayed when visitors are scrolling through the packages, projects and tools page.
      placeholder: e.g. NHSRplotthedots is an R package that simplifies the creation and automation of statistical process control (SPC) charts for KPIs. It helps analysts and teams move beyond static KPIs to understand true performance variation and identify opportunities for improvement.

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe what the tool, package or project does. Make sure to include details of the sort of outputs users might expect. Note that this section will be rendered within Quarto, so feel free to use all kinds of Quarto formatting. If you wish to include images, please add a placeholder within the file making it clear what image should be present there, and then upload these images to the github issue that will be created after you have submitted this. Alternatively, if the image is already hosted somewhere publicly accessible, you can include the URL of the image in this text box.
      render: markdown

  - type: input
    id: author
    attributes:
      label: Your Name
      placeholder: e.g. Alan Lyst

  - type: dropdown
    id: category
    attributes:
      multiple: true
      label: Category
      options:
        - Service Planning
        - Identifying Bottlenecks
        - Data Visualisation
        - Pathway Analytics
        - Statistical Process Control
        - KPI Reporting
        - Forecasting
        - Demand & Capacity Modelling
        - Other

  - type: input
    id: category_other
    attributes:
      label: If you ticked “Other” in the category, please specify, separating multiple categories with semicolons (;)
      placeholder: e.g. Workforce Modelling; Mental Health

  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - Bronze
        - Silver
        - Gold

  - type: textarea
    id: status_reason
    attributes:
      label: Status Reason
      description: Describe why you have given this project, tool or package this ranking. If you have ranked it Bronze or Silver, explain what is preventing you from ranking it more highly. Give a brief justification of why you feel this ranking is appropriate.
      render: markdown

  - type: input
    id: code
    attributes:
      label: Repository URL
      placeholder: e.g. https://nhsrplotthedots.nhsrcommunity.com/

  - type: input
    id: documentation
    attributes:
      label: Documentation URL
      placeholder: e.g. https://github.com/org/model-name

  - type: input
    id: pypi
    attributes:
      label: PyPi URL
      placeholder: e.g. https://github.com/org/model-name

  - type: input
    id: cran
    attributes:
      label: CRAN URL
      placeholder: https://cran.r-project.org/web/packages/NHSRplotthedots/index.html

  - type: input
    id: website
    attributes:
      label: Website URL
      placeholder: https://cran.r-project.org/web/packages/NHSRplotthedots/index.html

  - type: dropdown
    id: language
    attributes:
      label: Language or Tool 
      multiple: true
      options:
        - Python
        - R
        - Julia
        - PowerBI
        - Tableau
        - PowerApps
        - SQL

  - type: input
    id: language_other
    attributes:
      label: If you ticked “Other” in the language or tool input, please specify, separating multiple entries with semicolons (;)
      placeholder: e.g. Databricks
