---
title: "Books, Training and Communities"
toc: false
include-back-link: false
grid:
  sidebar-width: 0px
  body-width: 1100px
  margin-width: 300px
  gutter-width: 1.5rem

format:
  html:
    template-partials:
      - /resources/partials/small/title-block.html

listing:

  - id: books-healthcare
    type: grid
    grid-columns: 2
    categories: true
    template: ../packages_projects_tools/listing.ejs
    sort: Title
    contents: "*/*.qmd"
    page-size: 1000
    include:
      categories: Books
    exclude:
      categories:
        - General Open Analytics
        - Paid Resources

  - id: books-general
    type: grid
    grid-columns: 2
    template: ../packages_projects_tools/listing.ejs
    sort: Title
    contents: "*/*.qmd"
    page-size: 1000
    include:
      categories: General Open Analytics
    exclude:
      categories:
        - Paid Resources

  - id: books-paid
    type: grid
    grid-columns: 2
    template: ../packages_projects_tools/listing.ejs
    sort: Title
    contents: "*/*.qmd"
    page-size: 1000
    include:
      categories: Paid Resources

  - id: training-courses
    type: grid
    grid-columns: 2
    template: ../packages_projects_tools/listing.ejs
    sort: Title
    contents: "*/*.qmd"
    page-size: 1000
    include:
      categories: Courses
    exclude:
      categories:
        - Books
        - Communities

  - id: training-interactive
    type: grid
    grid-columns: 2
    template: ../packages_projects_tools/listing.ejs
    sort: Title
    contents: "*/*.qmd"
    page-size: 1000
    include:
      categories: Interactive Learning Tools
    exclude:
      categories:
        - Books
        - Communities

  - id: training-reference
    type: grid
    grid-columns: 2
    template: ../packages_projects_tools/listing.ejs
    sort: Title
    contents: "*/*.qmd"
    page-size: 1000
    include:
      categories: Reference Sites
    exclude:
      categories:
        - Books
        - Communities

  - id: communities
    type: grid
    grid-columns: 2
    template: ../packages_projects_tools/listing.ejs
    sort: Title
    contents: "*/*.qmd"
    page-size: 1000
    include:
      categories: Communities
---

This page contains books, courses, tutorials, interactive learning tools and communities of practice that may be of use to people wanting to build their skills in healthcare analytics, modelling and data science.

Looking for code packages, projects or tools? Head to the [Packages, Projects and Tools](/packages_projects_tools/index.qmd) page.

**Want to suggest an addition to this page? Head to our [contributor guide](/contributing/index.qmd) to find out more - coding entirely optional.**

::: {.value-box color="rgb(211, 123, 0)" width="100%" min-height="180px" font-size="1rem"}

Please note that inclusion of a resource on this site does not imply that the HSMA team, NIHR, or any other Atlas contributors, have reviewed these resources in detail. This resource is designed to act as a signpost to the work that is out there, but **you should always conduct your own reviews of the suitability of any of these resources for your own use case.**

Inclusion of a resource on this page also does not indicate endorsement of the resource author of the HSMA programme, NIHR, the Atlas, or the description written of the resource.

If you have any concerns, or would like any content to be removed, please [raise an issue on the repository](https://github.com/hsma-programme/decision_intelligence_atlas/issues/new/choose).

:::

<br>

<i class="fa-solid fa-hospital"></i> indicates a resource has been written by a team in the NHS, Public Health England, or a similar organisation

<i class="fa-solid fa-user-graduate"></i> indicates a resource has been written by academics, though often they will be working in partnership with NHS organisations in some manner

<i class="fa-solid fa-sterling-sign"></i> indicates a resource is not free to access

## Books

Books and eBooks covering analytics, modelling and data science techniques. Most are free to read online; paid books are listed separately at the end of this section.

### Healthcare-specific

Books written for, or built around examples from, health and care settings.

::: {#books-healthcare}
:::

### General open analytics

Open books on analytics, modelling and data science that are not specific to healthcare, but are useful for healthcare analysts.

::: {#books-general}
:::

### Paid books

Books that must be bought or accessed through a paid subscription. These are marked with <i class="fa-solid fa-sterling-sign"></i>.

::: {#books-paid}
:::

## Training

### Courses

Structured courses and modules, often including recorded sessions, slides and exercises.

::: {#training-courses}
:::

### Interactive tools

Interactive apps and tools to help you explore and learn concepts hands-on.

::: {#training-interactive}
:::

### Reference sites

Websites with code snippets, guides and reference material to dip into as needed.

::: {#training-reference}
:::

## Communities

Professional networks and communities of practice where healthcare analysts can connect, share their work and learn from each other.

::: {#communities}
:::
