---
title: "Packages, Projects and Tools"
toc-location: right
include-back-link: false
grid:
  sidebar-width: 0px
  body-width: 1100px
  margin-width: 300px
  gutter-width: 1.5rem
listing:
    - id: kpi_reporting
      contents: "*/*.qmd"
      sort: "title asc"
      type: grid
      include:
        categories: "{KPI Reporting}"
      grid-columns: 2
      page-size: 1000
      categories: true
      template: listing.ejs
      template-params:
        ncols: 2
      sort-ui: true
      filter-ui: true
      image-placeholder: "../resources/placeholder.png"
    - id: analysing_and_improving_pathway_performance
      include:
        categories: "{Pathway Analytics,Identifying Bottlenecks}"
      contents: "*/*.qmd"
      sort: "title asc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: true
      template: listing.ejs
      template-params:
        ncols: 2
      sort-ui: true
      filter-ui: true
      image-placeholder: "../resources/placeholder.png"
    - id: demand_forecasting
      contents: "*/*.qmd"
      sort: "title asc"
      type: grid
      include:
        categories: "{Forecasting,Demand Prediction}"
      grid-columns: 2
      page-size: 1000
      categories: true
      template: listing.ejs
      template-params:
        ncols: 2
      sort-ui: true
      filter-ui: true
      image-placeholder: "../resources/placeholder.png"
    - id: web_interface_and_tool_creation
      contents: "*/*.qmd"
      sort: "title asc"
      type: grid
      include:
        categories: "{Web Interface Creation}"
      grid-columns: 2
      page-size: 1000
      categories: true
      template: listing.ejs
      template-params:
        ncols: 2
      sort-ui: true
      filter-ui: true
      image-placeholder: "../resources/placeholder.png"
    - id: report_automation
      contents: "*/*.qmd"
      sort: "title asc"
      type: grid
      include:
        categories: "{Report Automation}"
      grid-columns: 2
      page-size: 1000
      categories: true
      template: listing.ejs
      template-params:
        ncols: 2
      sort-ui: true
      filter-ui: true
      image-placeholder: "../resources/placeholder.png"
    - id: other
      include:
        categories: "{Other}"
      contents: "*/*.qmd"
      sort: "title asc"
      type: grid
      grid-columns: 2
      page-size: 1000
      categories: true
      template: listing.ejs
      template-params:
        ncols: 2
      sort-ui: true
      filter-ui: true
      image-placeholder: "../resources/placeholder.png"
---

```{=html}
    <style>
    h2 {
    text-transform: uppercase;
    font-weight: 400;
    text-align: left;
}
    </style>
```

::: callout-warning
Please note that inclusion of a tool on this site does not imply that the HSMA team have reviewed these tools in detail. This is designed to act as a signpost to the work out there, and provide a high-level indication of the health of any given project, but you should always conduct your own reviews of the suitability of any of these tools and techniques for your own use case.

Inclusion of a tool on this page also does not indicate endorsement of the tool author of the HSMA programme or the description written of the tool.

If you have any concerns, or would like any content to be removed, please contact [Sammi Rosser](mailto:hi@sammirosser.com) or [raise an issue on the repository]().
:::

:::{.callout-note appearance="simple" collapse="true"}

### Click here to view what the project statuses mean

+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Status | Description                                                                                                                                                               |
+========+===========================================================================================================================================================================+
| Bronze | A script, tool or package with limited documentation and/or that may need significant reworking to be reused.                                                             |
|        |                                                                                                                                                                           |
|        | This may also be used to denote a project at an earlier stage of development, or which may no longer be maintained/receiving updates.                                     |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Silver | Either                                                                                                                                                                    |
|        |                                                                                                                                                                           |
|        | -   a script that is not optimised for reusability, but is well-documented and has scope for adapting                                                                     |
|        |                                                                                                                                                                           |
|        | -   a web-based or other tool with adjustable parameters                                                                                                                  |
|        |                                                                                                                                                                           |
|        | -   a package                                                                                                                                                             |
|        |                                                                                                                                                                           |
|        | However, compared to a 'gold' ranked project, these projects may be more limited in terms of automated tests, documentation, or may have limited adoption or maintenance. |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Gold   | Either                                                                                                                                                                    |
|        |                                                                                                                                                                           |
|        | -   a well-parameterised script that is easily adapted for new use cases, with excellent documentation                                                                    |
|        |                                                                                                                                                                           |
|        | -   a web-based or other tool with adjustable parameters                                                                                                                  |
|        |                                                                                                                                                                           |
|        | -   a package                                                                                                                                                             |
|        |                                                                                                                                                                           |
|        | All would be expected to have extensive tests, clear documentation, and be well-established projects that are actively maintained.                                        |
+--------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

:::

## Analysing and Improving Pathway Performance

::: {#analysing_and_improving_pathway_performance}
:::

## Automation of Reporting

::: {#report_automation}

:::

## Demand Forecasting

::: {#demand_forecasting}
:::

## KPI Reporting

::: {#kpi_reporting}
:::

##  Web-based Tools and Interacive Interface Creation

::: {#web_interface_and_tool_creation}
:::

##  Other

::: {#other}
:::
