# .github/workflows/quarto-check.yml
on:
  pull_request:

name: Quarto Check

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.33

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: atlas
          environment-file: environment.yaml
          miniforge-version: latest
          python-version: 3.12
          auto-activate-base: false

      - run: python -m pip install jupyter

      - name: Render (test build)
        run: quarto render
